pool:
  vmImage: windows-2019

#variables:
#  BuildConfiguration: Debug
#  MajorVersion: 1
#  MinorVersion: 2

name: $(MajorVersion).$(MinorVersion).$(Date:yyyyMMdd).$(Rev:r)

steps:

#- script: echo $(Build.BuildNumber)
#- script: echo $(Build.BuildId)
#- script: echo $(Build.DefinitionName)
#- script: echo $(Build.SourceBranchName)

- task: UseDotNet@2
  displayName: 'Use .NET Core SDK 3.1.x'
  inputs:
    version: 3.1.x

- task: NuGetToolInstaller@1
  displayName: 'Use NuGet 4.9.x'
  inputs:
    versionSpec: 4.9.x

#- task: gittools.gitversion.gitversion-task.GitVersion@5
- task: GitVersion@5
  inputs:
    runtime: 'core'
    configFilePath: 'gitversion.yml'
    updateAssemblyInfo: true

#- task: bleddynrichards.Assembly-Info-Task.Assembly-Info-NetCore.Assembly-Info-NetCore@2
#  displayName: Version
#  inputs:
#    VersionNumber: $(MajorVersion).$(MinorVersion).0.0
#    FileVersionNumber: $(MajorVersion).$(MinorVersion).*.*
#    InformationalVersion: $(MajorVersion).$(MinorVersion).*.*
#    PackageVersion: $(MajorVersion).$(MinorVersion).*.*

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: VSTest@2
  displayName: Test
  inputs:
    codeCoverageEnabled: true
    diagnosticsEnabled: true

- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: pack
    nobuild: true
    includesymbols: true
    includesource: true
    versioningScheme: byEnvVar 
    versionEnvVar: GitVersion.NuGetVersion

- task: NuGetCommand@2
  displayName: 'NuGet Push'
  inputs:
    command: push
    packagesToPush: $(Build.ArtifactStagingDirectory)/**/*.nupkg
    nuGetFeedType: external
    publishFeedCredentials: NuGet
