# Set triggers in the pipeline configuration
#trigger:
#  batch: true
#  branches:
#    include:
#    - master
#    - develop

#pr:
#  branches:
#    include:
#    - master

pool:
  vmImage: windows-2019

# Set variables in the pipeline configuration
#variables:
#  BuildConfiguration: Debug

# Build name
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml
#name: $(MajorVersion).$(MinorVersion).$(Date:yyyyMMdd).$(Rev:r)

steps:

# Debug environment variables
#- script: echo $(Build.BuildNumber)
#- script: echo $(Build.BuildId)
#- script: echo $(Build.DefinitionName)
#- script: echo $(Build.SourceBranchName)

# DotNet Core 2.x
# Required by GitVersion tool
- task: UseDotNet@2
  displayName: 'Install DotNet Core 2.x'
  inputs:
    packageType: runtime
    version: 2.x

# DotNet Core 3.1
- task: UseDotNet@2
  displayName: 'Install DotNet Core SDK 3.1.x'
  inputs:
    packageType: sdk
    version: 3.1.x

# NuGet 4.9
# We need .snupkg symbol support
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet 4.9.x'
  inputs:
    versionSpec: 4.9.x

# Version
# https://gitversion.net/docs/build-server-support/build-server/azure-devops
- task: GitVersion@5
  displayName: 'Run GitVersion Tool'
  inputs:
    runtime: core
    configFilePath: gitversion.yml

# Test
- task: DotNetCoreCLI@2
  displayName: 'Run DotNet Core Tests'
  inputs:
    command: test
    projects: 'UtilitiesTests/UtilitiesTests.csproj'
    configuration: $(BuildConfiguration)
    publishTestResults: true

# Build
- task: DotNetCoreCLI@2
  displayName: 'Build DotNet Core'
  inputs:
    command: build
    projects: 'Utilities/Utilities.csproj'
    configuration: $(BuildConfiguration)
    versioningScheme: byEnvVar
    versionEnvVar: GitVersion.SemVer

# Pack
- task: DotNetCoreCLI@2
  displayName: 'Pack DotNet Core'
  inputs:
    command: pack
    nobuild: true
    includesymbols: true
    includesource: true
    versioningScheme: byEnvVar 
    versionEnvVar: GitVersion.NuGetVersion

# Push
# Use NuGet command task instead of dotnet push so we can get .snupkg symbol support
- task: NuGetCommand@2
  displayName: 'Push NuGet'
  inputs:
    command: push
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
    nuGetFeedType: external
    publishFeedCredentials: NuGet
