pool:
  name: windows-2019

variables:
  BuildConfiguration: Debug
  MajorVersion: 1
  MinorVersion: 2

name: ​​​$(MajorVersion).$(MinorVersion).$(DayOfYear).$(Rev:r)

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK 3.1.x'
  inputs:
    version: 3.1.x

- task: NuGetToolInstaller@1
  displayName: 'Use NuGet 4.9.x'
  inputs:
    versionSpec: 4.9.x

- task: bleddynrichards.Assembly-Info-Task.Assembly-Info-NetCore.Assembly-Info-NetCore@2
  displayName: Version
  inputs:
    VersionNumber: $(MajorVersion).$(MinorVersion).0.0
    FileVersionNumber: $(MajorVersion).$(MinorVersion).$(DayOfYear).$(Rev:r)
    InformationalVersion: $(MajorVersion).$(MinorVersion).$(DayOfYear).$(Rev:r)
    PackageVersion: $(MajorVersion).$(MinorVersion).$(DayOfYear).$(Rev:r)

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: VSTest@2
  displayName: Test
  inputs:
    codeCoverageEnabled: true
    diagnosticsEnabled: True

- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: pack
    nobuild: true
    includesymbols: true
    includesource: true
    versioningScheme: byBuildNumber

- task: NuGetCommand@2
  displayName: 'NuGet Push'
  inputs:
    command: push
    packagesToPush: $(Build.ArtifactStagingDirectory)/**/*.nupkg
    nuGetFeedType: external
    publishFeedCredentials: NuGet
