using System.IO.Compression;
using System.Runtime.CompilerServices;

namespace ptr727.Utilities;

/// <summary>
/// Provides extension methods for string compression.
/// </summary>
[System.Diagnostics.CodeAnalysis.SuppressMessage(
    "Design",
    "CA1034:Nested types should not be visible",
    Justification = "The visible nested type is generated by the C# extension members feature; https://github.com/dotnet/sdk/issues/51681"
)]
public static class CompressExtensions
{
    /// <summary>
    /// Extension methods for string compression and decompression.
    /// </summary>
    extension(string uncompressedString)
    {
        /// <summary>
        /// Compresses the string using Deflate compression.
        /// </summary>
        /// <param name="compressionLevel">The compression level to use.</param>
        /// <returns>A Base64-encoded compressed string.</returns>
        public string Compress(CompressionLevel compressionLevel = CompressionLevel.Optimal) =>
            StringCompression.Compress(uncompressedString, compressionLevel);

        /// <summary>
        /// Compresses the string asynchronously using Deflate compression.
        /// </summary>
        /// <param name="compressionLevel">The compression level to use.</param>
        /// <param name="cancellationToken">The cancellation token.</param>
        /// <returns>A Base64-encoded compressed string.</returns>
        public Task<string> CompressAsync(
            CompressionLevel compressionLevel = CompressionLevel.Optimal,
            CancellationToken cancellationToken = default
        ) =>
            StringCompression.CompressAsync(
                uncompressedString,
                compressionLevel,
                cancellationToken
            );

        /// <summary>
        /// Decompresses a Base64-encoded compressed string.
        /// </summary>
        /// <returns>The decompressed string.</returns>
        public string Decompress() => StringCompression.Decompress(uncompressedString);

        /// <summary>
        /// Decompresses a Base64-encoded compressed string asynchronously.
        /// </summary>
        /// <param name="cancellationToken">The cancellation token.</param>
        /// <returns>The decompressed string.</returns>
        public Task<string> DecompressAsync(CancellationToken cancellationToken = default) =>
            StringCompression.DecompressAsync(uncompressedString, cancellationToken);
    }
}

/// <summary>
/// Provides logger error handling helpers and strongly-typed, source-generated log messages.
/// </summary>
internal static partial class LogExtensions
{
    /// <summary>
    /// Extension methods for Microsoft.Extensions.Logging ILogger error handling.
    /// </summary>
    extension(ILogger logger)
    {
        /// <summary>
        /// Logs an exception and returns false to allow error propagation in catch-when clauses.
        /// </summary>
        /// <param name="exception">The exception to log.</param>
        /// <param name="function">The function name (automatically captured).</param>
        /// <returns>Always returns false to allow exception to propagate.</returns>
        internal bool LogAndPropagate(
            Exception exception,
            [CallerMemberName] string function = "unknown"
        )
        {
            logger.LogCatchException(function, exception);
            return false;
        }

        /// <summary>
        /// Logs an exception and returns true to indicate exception handling in catch-when clauses.
        /// </summary>
        /// <param name="exception">The exception to log.</param>
        /// <param name="function">The function name (automatically captured).</param>
        /// <returns>Always returns true to indicate exception was handled.</returns>
        internal bool LogAndHandle(
            Exception exception,
            [CallerMemberName] string function = "unknown"
        )
        {
            logger.LogCatchException(function, exception);
            return true;
        }
    }

    [LoggerMessage(Message = "Exception in {Function}", Level = LogLevel.Error)]
    internal static partial void LogCatchException(
        this ILogger logger,
        string function,
        Exception exception
    );

    [LoggerMessage(
        Message = "Deleting ({RetryCount} / {OptionsRetryCount}) : {FileName}",
        Level = LogLevel.Information
    )]
    internal static partial void LogDeletingFile(
        this ILogger logger,
        int retryCount,
        int optionsRetryCount,
        string fileName
    );

    [LoggerMessage(
        Message = "Deleting ({RetryCount} / {OptionsRetryCount}) : {Directory}",
        Level = LogLevel.Information
    )]
    internal static partial void LogDeletingDirectory(
        this ILogger logger,
        int retryCount,
        int optionsRetryCount,
        string directory
    );

    [LoggerMessage(
        Message = "Renaming file failed due to invalid path(s) : {OriginalName} to {NewName}",
        Level = LogLevel.Error
    )]
    internal static partial void LogRenameInvalidPath(
        this ILogger logger,
        string originalName,
        string newName
    );

    [LoggerMessage(
        Message = "Renaming ({RetryCount} / {OptionsRetryCount}) : {OriginalDirectory} : {OriginalFile} to {NewFile}",
        Level = LogLevel.Information
    )]
    internal static partial void LogRenamingInDirectory(
        this ILogger logger,
        int retryCount,
        int optionsRetryCount,
        string originalDirectory,
        string originalFile,
        string newFile
    );

    [LoggerMessage(
        Message = "Renaming ({RetryCount} / {OptionsRetryCount}) : {OriginalName} to {NewName}",
        Level = LogLevel.Information
    )]
    internal static partial void LogRenaming(
        this ILogger logger,
        int retryCount,
        int optionsRetryCount,
        string originalName,
        string newName
    );

    [LoggerMessage(
        Message = "Waiting for file to become readable ({RetryCount} / {OptionsRetryCount}) : {Name}",
        Level = LogLevel.Information
    )]
    internal static partial void LogWaitingForReadable(
        this ILogger logger,
        int retryCount,
        int optionsRetryCount,
        string name
    );
}
